### ISSUE TITLE
"Typo" in README

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaStats/Klara.jl#145]
README: "Some of the old one has not been fully ported"

I assume "old code", I thought this had to do with Lora->Klara, but it seems not.

**Comment by scidom** [comment]
Thanks for the query @PallHaraldsson. You are right in that most of the functionality has been ported by now from an older version of Lora (more than a year old) to Klara. The main functionality still missing is adding back the NUTS sampler, on which I am working offline till I push it to Klara (normally it is one or two days work but might take a few extra days due to being on holidays), and also adding back the slice sampler. Then there are two more geometric samplers that are a bit more "exotic" (RMHMC and MMALA), by which time all old functionality will have been retrieved.

Other than this, a very generic Gibbs scheme will be added (there is already a Gibbs sampler in Klara, but want to add a superset of Roberts' AMWG sampler that will allow sampling for a wide range of models and wasn't available in older Lora), and then also add population MCMC and particle MCMC (the latter being part of a collaboration).

NUTS will be ready very soon.

**Comment by ararslan** [comment]
I think @PallHaraldsson's point was that "Some of the old one has not been fully ported" isn't grammatically correct in English, so he was wondering if "one" should have been "code."

**Comment by scidom** [comment]
Good point @aralsan, got it now, thanks for spotting this typo @PallHaraldsson.
